language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install coveralls
  - python setup.py develop
# command to run tests
script:
  - python setup.py test --addopts '--cov=elasticroute'
  
after_success:
  - coveralls