language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install coveralls
  - python setup.py develop
# command to run tests
script:
  - python setup.py test --addopts '--cov=elasticroute'
  
after_success:
  - coveralls
notifications:
  slack:
    secure:       vEKmzrD0Lf8emnT3tku/Q0+ccg2R9mU+58z0wObAX/MTslQDzOTxA0Jt1H0om6lLj4H8MOFdbpHdkSKyDaP7c0woPk0n0kFpa+ZVepZnyudY6+Ceq9EMMLB/ml08UBnxqdct42QccTcnbqXn0GqF97OTUyrPGZeME0CpjKt7+BC/+ospt84BLDTZTEXW7QzTHWqeWPc6Ib6O9vTJFvo8L91Es6A3TjQ2DEDrHmXc85CCr09AMa9KfhqiEJ/MtpFBc7laShH4DGtBsJv0/XPre/a3FK6VEDaW6wDlhkKGd6TA/oc8pFGX7FT9T4cbcYvmvaxzyLd2b5JrkfeRYhzyZlD0EZQ5o9IekPEc2lI+bZc5CZne6irqgl7eiEvZ+6ZrKlKVwg/+UOghgwvgKuWLrGtkdSt50irtNyPUJekkGsT9oCo1TCFFay/FNeXuY1V8bvQqWjBaO/36gQy+rm9+M3nS6QPehBP3g5w8C61d/BA20RAc9Zml28YaQ1fxoFTAQpREsKKG2iWxTHe6FXK9JGYfy0N6J+bvRJUuLjipX0zN1aMtJViqGyTXil0e9n9P3/YBH6hami4Uf0I/HMwtRvfzKVGadVzMKrIL4ktbi8ND1G8ku3AdMzpvUI4WVuoCoT7k3NQMFjXu0jGlEQ8cmMINVFlbqO9LcQgv75dbNyk=
