dist: xenial
language: python
python:
- '3.6'
- '3.7'
install:
- pip install coveralls
- python setup.py develop
script:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
- python setup.py test --addopts '--cov=elasticroute'
after_success:
- coveralls
notifications:
  slack:
    secure: E5VNDFS5Q3w6p6gZl6SrOJx4lHcy+z+C0K8sAN7VvUwnpWvlPY2dbT4flaiMqIHubs2BzXgyRr/KwdOhMGvgq0t6NKWiEJ4sCat6hSlhclnWGO28G8JC5Ux2Tk0RJZctXsljRkuFn46lAwMswlIP3AV5FLx9p39HgGPPsG9AEW/mw5Nw5LU6DLubh7U3mlYRwXcM5AaoVAHzgXv7+sEciWndSfMeWSbgM6CeSn/6pLVgP6k3xFsDy0jSWD7UqpumzVy/Qu56+Ac+6Qj1fwhtAx50UAsLAgbvg+48HynuyoxVd9EPRr2RZdFuJtYdMYh6cNSy7jmYX7bPhRLR+17XztH3me1uFl0Ceqb69dvaEXDk1p1Okk3aLMEY5odJ5OGH8uPsAoFfdOuAvlDAGPt0nF7/5RoO1gtOngzaENQvkiAl8zjtFchoqsrIP2ci/06dzV3OvgtwzAi5xOUJLrUhvjxuS/tfrWcY0aw7XEixk56CXX8MD6Mxq3+yB4FZ8G8FtQ7cRRPC6JZOOToXSE6mPP5w0OG2l8ley6iOLsrlE6RCkm+1nFYJ/sbXhMJvaLlcb7hr40y+2h07fAoB5L9v5yQCSQOWmNH/nJYXi79SxT8I4IJTR1BhDxJjC4bAp/Gy5gLOLXQnWcD4LxGyfmfKjP0ESP5TrQbUbXQoRMWm5oQ=
