dist: xenial
language: python
python:
- '3.6'
- '3.7'
install:
- pip install coveralls
- python setup.py develop
script:
- python setup.py test --addopts '--cov=elasticroute'
after_success:
- coveralls
notifications:
  slack:
    secure: k1pdQZB5/WUdy+eLSJ/0vP5tVcKScHPJcRe4bwyUsANjoGNeWOrPW78pE/IXBMiCghMlsoBBkkp//q0r9t9liGuI5qiBSmSECwZFiEbcaQic/phsBEWxs8j6whDe5kqNoBeZSnimRWNpJjEsLxY28pxIcU5WJitYlkdh6Jv/AQIMksDsvOWNbPvNX7zvKWsVspgfSeJ8nsvQV9pW91a/wgaSnYKmwyTh2R48dd2cpo3DCwQDXvJ6WrsLts7W2WbuPqGyIaZZ2TUbzz17cReF7XFBj3hRlZD6mbhpK36ri+5ZftYmMU10ppgXUypFf40gCRxb9qIbOXAHeFOMudlUQtwWHLBjfi8x9GVZGbpcPMg4tg2u1JLRo9xINJLrVEAK1S3fjaZL72m+PhvHPNP9lwGKIlZzTCW0OEyOzoaRx8xebL/4odFz4yz7lii2H1wSBZVHdGDhkQAlBKxWEL81NH6wZAXdiurSYJzAmmD+qDpvvIJqZ2o1Efi7+TnR5J5ONbInlKRHn9TXoSgQRkS9kXUewDODg9hiTjnMgPPJa/Ku0F7Ld9spaj/2fNO/QSWgWEmq2VuprJ6Wa/zkilOPpCRykjpR9IgbtfP1U1XKe8LAjcpOYj7HvwewkHO9Diu0Xnx7+/rYSqM7IbIxrzuqqbGm3/+B94Z8OaMZUb/+qj0=
